### ISSUE TITLE
How can be free of dayitem selection?

### ISSUE THREAD

**Issue by oddukgi** [retailcrm/Fastis#2]
Hello? I want to show date until this date on calendar.
 `calendarConroller.maximumDate = Date()`
If date is Sep 6 and it show Oct 5.
I don't want to show future month.
Is there any way ?

**Comment by ilia3546** [comment]
Hello @oddukgi,
Thank you for your suggestion. Unfortunately we haven't free time to solve this now. But you can feel free to make an PR with you solution :)
